version: '3'
services:
  location-service:
    build:
      context: .
    container_name: "kayako-service-location-master"
    labels:
      com.trilogy.company: "ignite"
      com.trilogy.team: "MS.DockerProduction"
      com.trilogy.product: "firstrain"
      com.trilogy.service: "base-rc"
      com.trilogy.stage: "prod"
      com.trilogy.maintainer.skype: "blessenjacob"
      com.trilogy.maintainer.email: "blessen.jacob@aurea.com"
